### ISSUE TITLE
Error 0x0000003d help(((

### ISSUE THREAD

**Issue by Boomkuze** [Broihon/GH-Injector-GUI#10]
![1](https://user-images.githubusercontent.com/111609736/188028774-64e11fce-65c4-4826-b9f3-1afc159ab469.PNG)
![123132](https://user-images.githubusercontent.com/111609736/188028778-9936c54d-3b9f-469a-a04d-5529bc314f90.PNG)

**Comment by LucasWG** [comment]
estou com esse mesmo erro
descobriu como arrumar?

**Comment by LucasWG** [comment]
I have this same error
did you find out how to fix it?
