### ISSUE TITLE
Shortcut doesn't work

### ISSUE THREAD

**Issue by StixuYT** [Broihon/GH-Injector-GUI#11]
When in the GUI, everything works perfectly fine (injecting .dll into game process, unhooking the cheat, then re-injecting) doing this process infinite times works no problem, when I try and create a shortcut, it works the first time, but never works after that, not even restarting computer works, I have to inject with normal GUI first and then the shortcut works one-time, never again after that. 

https://streamable.com/qx5xan the video where it happens

**Comment by Broihon** [comment]
Use scramble dll name with load dll copy (or neither) when using a shortcut. The shortcut (which contains the file path in its arguments) doesn't update itself - unlike the GUI (at 0:09 and 0:26 (see console)) - if you just scramble the file name.

**Comment by StixuYT** [comment]
Disabling the scramble dll name worked, but how can I inject from a batch file? for example, I tried to use this command
start "" "C:\Windows\DigitalLocker\GH Injector - x64.exe" --p "csgo.exe" --f "C:\Windows\DigitalLocker\cheat.dll" --timeout 1000 --log --l 4 --s 4 --mmflags 1ee0000 --wait 

this is the properties outcome from the shortcut **without** dll name scramble, but it gets stuck here(the same stage as before, when scramble dll name was checked) 
https://prnt.sc/lKo2c7nr3DE_

**Comment by Broihon** [comment]
Why the double hyphens?

**Comment by StixuYT** [comment]
Oh my God....the double hyphens were the problem. 
As for the failure to find LdrpInvertedFunctionTables, even with the GUI, in console I also get that error, I use Windows 10 22H2(OS Build 19045.2486) the thing is I manually created my .iso for this windows install to remove microsoft shitty bloatware(removed everything, but kept stuff like Microsoft.Camera,Microsoft.Photos, etc..) perhaps my custom build of windows is the issue? even though it only removes **only apps** from microsoft

**Comment by Broihon** [comment]
Glad it work, gonna close the issue for now. Will def. look into the LdrpInvertedFunctionTables issue though. Really weird.
