### ISSUE TITLE
Any way to make the shortcut's cmd window invisible?

### ISSUE THREAD

**Issue by StixuYT** [Broihon/GH-Injector-GUI#12]
https://prnt.sc/wNtJxWX1C9Ou

make this window invisible so it injects in the background

**Comment by Broihon** [comment]
Currently not implemented. I could implement something like a "-silent" option that wouldn't spawn a console. Then you'd get absolutely no feedback though whether the injection succeeded, failed or even happend.

**Comment by Broihon** [comment]
-silent has been implemented. Just generate the shortcut normally and click yes when asked to make the shortcut silent.
