### ISSUE TITLE
Mind uploading the build here on github? Downloading QT just to build this seems like an overkill.

### ISSUE THREAD

**Issue by dumbasPL** [Broihon/GH-Injector-GUI#15]

**Comment by dumbasPL** [comment]
[GH Injector.zip](https://github.com/Broihon/GH-Injector-GUI/files/11012220/GH.Injector.zip)

Fuck it, here is a static build in case anyone needs. I'm still mad this isn't in the releases section

**Comment by Broihon** [comment]
No.

**Comment by dumbasPL** [comment]
why not?
