### ISSUE TITLE
Auto Inject

### ISSUE THREAD

**Issue by 1i8** [Broihon/GH-Injector-GUI#16]
Hello, I have a question about a possible addition to the auto inject feature that allows it to remain enabled after successful injection, so that the DLL is automatically injected every time the user opens the process while auto inject is enabled. Thanks in advance.

**Comment by Broihon** [comment]
I specifically decided against this as this would lead to confusions with some processes that have already be injected into.
I'd essentially have to keep track which DLL was injected into which process to not accidentally repeat the injection if the user didn't intend to do so.
