### ISSUE TITLE
ERROR (" The code execution cannot proceed because clang_rt.asan_dbg_dynamicc-86_64.dll was not found. Reinstalling the program may fix this problem.")

### ISSUE THREAD

**Issue by homixidemichi** [Broihon/GH-Injector-GUI#17]
when I run GH Injector it saids " The code execution cannot proceed because clang_rt.asan_dbg_dynamicc-86_64.dll was not found. Reinstalling the program may fix this problem."

Someone please lmk what i can do!

Discord just in case: zo#0005 

![image](https://user-images.githubusercontent.com/127697083/236135698-7c6fa286-094f-467e-9367-75122e4f02ac.png)

**Comment by Broihon** [comment]
No clue. This is a VS related issue. Check this thread:
https://developercommunity.visualstudio.com/t/clang-rtasan-dbg-dynamic-x86-64dll-was-not-found-w/1140325
