### ISSUE TITLE
v4.4 bug cant use.

### ISSUE THREAD

**Issue by alloidiota** [Broihon/GH-Injector-GUI#3]
windows pro 10 21h1 19043.1149
gh v4.4 compiled from source as release x64 qt 5.15.0 and static x64. When open injector, PDB download appear,

```
The injector requires PDB files for the ntdll.dll to work.
These files will be downloaded from the Microsoft Symbol Server
and will take up about 3MB.
Do you want to download the files now?
```

i click yes, then files being downloaded to 100%, after that its says
```
Download/import failure. Error code: 0x0000003d
The injector cannot function without the PDB files.
Please restart the injector.
```

But in GH folder there appear new 2 folders "x64", "x86". And files in them "x64\ntdll.pdb" for 1587kb, "x86\ntdll.pdb" for 1603 kb.
After restart injector happeng same things. But files not being downloaded. SO i cant use injector.
Made all instructions.
Actually tried to build with various parameters and sdk, still same.
Am i doing something wrong or source is broken? Maybe GH Library source errors?

**Comment by Broihon** [comment]
For import resolving (wow64) the injector needs "GH Injector SM - x86.exe" to be in the same directory. This is part of the [GH Injection Library](https://github.com/Broihon/GH-Injector-Library).

**Comment by alloidiota** [comment]
All working now. Thank you :3
