### ISSUE TITLE
error code 0x00000003d The injector cannot function without the pdb files. please restart the injector

### ISSUE THREAD

**Issue by w5b** [Broihon/GH-Injector-GUI#9]
hi, i compiled everything and im getting this error everytime i open the injector. im pressing on download pdb files and always getting this error.

**Comment by w5b** [comment]
fixed by clicking the version and redownoading.

**Comment by Broihon** [comment]
The x86 files need to be in the same directory (specifically "GH Injector SM - x86.exe") for import resolving.
